export default {
  login: "timilsina-devi",
  id: 49350389,
  node_id: "MDQ6VXNlcjQ5MzUwMzg5",
  avatar_url: "https://avatars3.githubusercontent.com/u/49350389?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/timilsina-devi",
  html_url: "https://github.com/timilsina-devi",
  followers_url: "https://api.github.com/users/timilsina-devi/followers",
  following_url:
    "https://api.github.com/users/timilsina-devi/following{/other_user}",
  gists_url: "https://api.github.com/users/timilsina-devi/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/timilsina-devi/starred{/owner}{/repo}",
  subscriptions_url:
    "https://api.github.com/users/timilsina-devi/subscriptions",
  organizations_url: "https://api.github.com/users/timilsina-devi/orgs",
  repos_url: "https://api.github.com/users/timilsina-devi/repos",
  events_url: "https://api.github.com/users/timilsina-devi/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/timilsina-devi/received_events",
  type: "User",
  site_admin: false,
  name: "Devi Timilsina",
  company: "Self, Looking for opportunities.",
  blog: "https://github.com/timilsina-devi",
  location: "Calgary",
  email: "timilsinadevipd@gmail.com",
  hireable: null,
  bio: "Recent Graduate, seeking for a software developer role.",
  twitter_username: "DeviTimilsina",
  public_repos: 3,
  public_gists: 0,
  followers: 10,
  following: 2,
  created_at: "2019-04-06T19:51:50Z",
  updated_at: "2021-01-05T08:31:46Z",
};
